# Generated by Django 2.1.1 on 2018-10-24 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_ing_ret',
            name='fecha_trabajo',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cad_ing_ret',
            name='ind_ing_egr',
            field=models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], default='I', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='cad_ing_ret',
            unique_together={('fecha_trabajo', 'num_veces_i')},
        ),
    ]
