# Generated by Django 2.1.1 on 2018-12-07 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cad_master',
            name='accesorapido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cad_v_mesas',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
