# Generated by Django 2.1.1 on 2019-01-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cad_est_finan',
            name='saldo_caja_neto',
        ),
    ]
