# Generated by Django 2.1.1 on 2018-11-28 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0002_auto_20181024_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_stock_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('fec_movimiento', models.DateField(default=datetime.datetime.now)),
                ('num_veces', models.SmallIntegerField()),
                ('cantidad_mov', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_insumo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ind_ing_sal', models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida')], default='I', max_length=1)),
                ('modo_pago_m', models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta')], default='E', max_length=1)),
                ('cod_insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastroCostos.Cad_insumos')),
            ],
        ),
        migrations.AddField(
            model_name='cad_v_mesas',
            name='estado',
            field=models.CharField(choices=[('O', 'Orden'), ('P', 'Pagado')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cad_stock_pedido',
            unique_together={('cod_insumo', 'fec_movimiento', 'num_veces')},
        ),
    ]
