# Generated by Django 2.1.1 on 2018-10-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0002_cad_v_mesas_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cad_v_mesas_detalle',
            name='cod_insumo',
        ),
    ]
