# Generated by Django 2.1.1 on 2018-10-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0003_remove_cad_v_mesas_detalle_cod_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_insumos',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
