# Generated by Django 2.1.1 on 2018-11-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0003_auto_20181128_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cad_v_mesas_detalle',
            unique_together={('cabecera', 'linea')},
        ),
    ]
