# Generated by Django 2.1.1 on 2018-11-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroCostos', '0004_auto_20181130_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_v_mesas_detalle',
            name='cantidad_venta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
